set custom bash prompt

diff --git a/bashrc.d/environment b/bashrc.d/environment
--- a/bashrc.d/environment
+++ b/bashrc.d/environment
@@ -11,3 +11,29 @@ HISTCONTROL=ignoreboth:erasedups
 # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
 HISTSIZE=10000
 HISTFILESIZE=20000
+
+PROMPT_COMMAND=__prompt_command    # Function to generate PS1 after CMDs
+
+__prompt_command() {
+    local EXIT="$?"                # This needs to be first
+    PS1=""
+
+    local CReset='\[\e[0m\]'
+
+    local CBlack='\[\e[0;30m\]'
+    local CRed='\[\e[0;31m\]'
+    local CGreen='\[\e[0;32m\]'
+    local CYellow='\[\e[1;33m\]'
+    local CBlue='\[\e[1;34m\]'
+    local CMagenta='\[\e[0;35m\]'
+    local CCyan='\[\e[0;36m\]'
+
+    PS1+="${CCyan}\u@\h${CReset}:${CBlue}\w${CReset}"
+
+    # show return code if it is not 0
+    if [[ $EXIT != 0 ]]; then
+      PS1+=" ${CRed}$EXIT${CReset}"
+    fi
+
+    PS1+="$ "
+}
